[package]
name = "to-do-dal"
version = "0.1.0"
edition = "2024"

[features]
json-file = ["serde_json", "serde"]

[dependencies]
serde = { version="1.0.228", optional = true }
serde_json = { version="1.0.149", optional = true }

